<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    protected static ?string $password;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'cin' => 'AB123456',
                'rib' => 'MA123456789012345678901234',
                'situationFamiliale' => 'Célibataire',
                'nbEnfants' => 0,
                'adresse' => 'Rabat',
                'name' => 'El Khattabi',
                'password' => static::$password ??= Hash::make('password'),
                'prenom' => 'Sara',
                'date_naissance' => '1990-03-15',
                'tel' => '0600000001',
                'email' => 'sara.khattabi@example.com',
                'role' => 'Employe',
                'statut' => 'Present',
                'typeContrat' => 'Permanent',
                'picture' => 'img1.png',
                'departement_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'CD789012',
                'rib' => 'MA987654321098765432109876',
                'situationFamiliale' => 'Marié',
                'nbEnfants' => 2,
                'adresse' => 'Casablanca',
                'name' => 'Benali',
                'password' => static::$password,
                'prenom' => 'Youssef',
                'date_naissance' => '1985-07-20',
                'tel' => '0600000002',
                'email' => 'youssef.benali@example.com',
                'role' => 'Manager',
                'statut' => 'Absent',
                'typeContrat' => 'CDD',
                'picture' => 'img2.png',
                'departement_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'EF345678',
                'rib' => 'MA112233445566778899001122',
                'situationFamiliale' => 'Divorcé',
                'nbEnfants' => 1,
                'adresse' => 'Tanger',
                'name' => 'Haddou',
                'password' => static::$password,
                'prenom' => 'Amal',
                'date_naissance' => '1992-12-01',
                'tel' => '0600000003',
                'email' => 'amal.haddou@example.com',
                'role' => 'Employe',
                'statut' => 'Malade',
                'typeContrat' => 'Stage',
                'picture' => 'img3.png',
                'departement_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'GH901234',
                'rib' => 'MA998877665544332211009988',
                'situationFamiliale' => 'Marié',
                'nbEnfants' => 3,
                'adresse' => 'Fès',
                'name' => 'Tazi',
                'password' => static::$password,
                'prenom' => 'Karim',
                'date_naissance' => '1980-01-10',
                'tel' => '0600000004',
                'email' => 'karim.tazi@example.com',
                'role' => 'Employe',
                'statut' => 'Congé',
                'typeContrat' => 'Permanent',
                'picture' => 'img4.png',
                'departement_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'IJ567890',
                'rib' => 'MA556677889900112233445566',
                'situationFamiliale' => 'Célibataire',
                'nbEnfants' => 0,
                'adresse' => 'Agadir',
                'name' => 'Ouardi',
                'password' => static::$password,
                'prenom' => 'Lina',
                'date_naissance' => '1995-05-05',
                'tel' => '0600000005',
                'email' => 'lina.ouardi@example.com',
                'role' => 'Employe',
                'statut' => 'Present',
                'typeContrat' => 'CDD',
                'picture' => 'img5.png',
                'departement_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'KL234567',
                'rib' => 'MA443322110099887766554433',
                'situationFamiliale' => 'Marié',
                'nbEnfants' => 2,
                'adresse' => 'Meknès',
                'name' => 'Fakih',
                'password' => static::$password,
                'prenom' => 'Samir',
                'date_naissance' => '1987-08-22',
                'tel' => '0600000006',
                'email' => 'samir.fakih@example.com',
                'role' => 'Manager',
                'statut' => 'Absent',
                'typeContrat' => 'Permanent',
                'picture' => 'img6.png',
                'departement_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'MN890123',
                'rib' => 'MA334455667788990011223344',
                'situationFamiliale' => 'Veuf',
                'nbEnfants' => 1,
                'adresse' => 'Oujda',
                'name' => 'Ziani',
                'password' => static::$password,
                'prenom' => 'Hassan',
                'date_naissance' => '1978-11-11',
                'tel' => '0600000007',
                'email' => 'hassan.ziani@example.com',
                'role' => 'Employe',
                'statut' => 'Malade',
                'typeContrat' => 'CDD',
                'picture' => 'img7.png',
                'departement_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'OP456789',
                'rib' => 'MA221133445566778899001122',
                'situationFamiliale' => 'Célibataire',
                'nbEnfants' => 0,
                'adresse' => 'Tétouan',
                'name' => 'Mimouni',
                'password' => static::$password,
                'prenom' => 'Nada',
                'date_naissance' => '1993-09-18',
                'tel' => '0600000008',
                'email' => 'nada.mimouni@example.com',
                'role' => 'Employe',
                'statut' => 'Congé',
                'typeContrat' => 'Stage',
                'picture' => 'img8.png',
                'departement_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'QR678901',
                'rib' => 'MA110022334455667788990011',
                'situationFamiliale' => 'Marié',
                'nbEnfants' => 4,
                'adresse' => 'El Jadida',
                'name' => 'Ait Said',
                'password' => static::$password,
                'prenom' => 'Omar',
                'date_naissance' => '1975-06-30',
                'tel' => '0600000009',
                'email' => 'omar.aitsaid@example.com',
                'role' => 'Manager',
                'statut' => 'Present',
                'typeContrat' => 'Permanent',
                'picture' => 'img9.png',
                'departement_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cin' => 'ST012345',
                'rib' => 'MA009988776655443322110099',
                'situationFamiliale' => 'Célibataire',
                'nbEnfants' => 0,
                'adresse' => 'Khouribga',
                'name' => 'Cherkaoui',
                'password' => static::$password,
                'prenom' => 'Salma',
                'date_naissance' => '1999-02-25',
                'tel' => '0600000010',
                'email' => 'salma.cherkaoui@example.com',
                'role' => 'Employe',
                'statut' => 'Absent',
                'typeContrat' => 'CDD',
                'picture' => 'img10.png',
                'departement_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
